Version: '2012-10-17'
Statement:
  - Sid: AllowGlobalUnrestrictedResourceActionsWhichIncurNoFees
    Effect: Allow
    Action:
      - ses:DescribeActiveReceiptRuleSet
      - ses:DescribeReceiptRuleSet
      - ses:CreateReceiptRuleSet
      - ses:DeleteReceiptRuleSet
      - ses:ListReceiptRuleSets
      - ses:SetActiveReceiptRuleSet
      - ses:GetIdentityNotificationAttributes
      - ses:GetIdentityVerificationAttributes
      - ses:GetIdentityDkimAttributes
      - ses:DeleteIdentity
      - ses:ListIdentities
      - ses:SetIdentityFeedbackForwardingEnabled
      - ses:SetIdentityHeadersInNotificationsEnabled
      - ses:SetIdentityNotificationTopic
      - ses:VerifyDomainIdentity
      - ses:VerifyDomainDkim
      - ses:SetIdentityDkimEnabled
      - ses:VerifyEmailIdentity
      - ses:GetIdentityPolicies
      - ses:PutIdentityPolicy
      - ses:DeleteIdentityPolicy
      - ses:ListIdentityPolicies
      - ssm:DescribeParameters
      - ssm:DescribeAssociation
      - ssm:GetDeployablePatchSnapshotForInstance
      - ssm:GetDocument
      - ssm:DescribeDocument
      - ssm:GetManifest
      - ssm:ListAssociations
      - ssm:ListInstanceAssociations
      - ssm:PutInventory
      - ssm:PutComplianceItems
      - ssm:PutConfigurePackageResult
      - ssm:UpdateAssociationStatus
      - ssm:UpdateInstanceAssociationStatus
      - ssm:UpdateInstanceInformation
      - ssm:StartSession
      - ssm:TerminateSession
      - ssmmessages:CreateControlChannel
      - ssmmessages:CreateDataChannel
      - ssmmessages:OpenControlChannel
      - ssmmessages:OpenDataChannel
      - ec2messages:AcknowledgeMessage
      - ec2messages:DeleteMessage
      - ec2messages:FailMessage
      - ec2messages:GetEndpoint
      - ec2messages:GetMessages
      - ec2messages:SendReply
      - codebuild:BatchGetProjects
      - codebuild:ListProjects
      - codecommit:ListRepositories
      - codepipeline:ListPipelines
      - codepipeline:GetPipeline
      - sqs:CreateQueue
      - sqs:DeleteQueue
      - sqs:GetQueueUrl
      - sqs:GetQueueAttributes
      - sqs:ListQueues
      - sqs:SetQueueAttributes
      - kinesis:ListStreams
      - kinesis:DescribeStream
      - cloudformation:DescribeStacks
      - cloudformation:ListExports
      - glue:GetTags
      - glue:TagResource
      - glue:UntagResource
    Resource: "*"
  - Sid: AllowGlobalResourceRestrictedActionsWhichIncurNoFees
    Effect: Allow
    Action:
      - ssm:PutParameter
      - ssm:DeleteParameter
      - ssm:GetParametersByPath
      - ssm:GetParameters
      - codebuild:CreateProject
      - codebuild:UpdateProject
      - codebuild:DeleteProject
      - codecommit:CreateRepository
      - codecommit:DeleteRepository
      - codecommit:GetRepository
      - codecommit:UpdateRepositoryDescription
      - codepipeline:CreatePipeline
      - codepipeline:DeletePipeline
      - codepipeline:UpdatePipeline
      - SNS:CreateTopic
      - SNS:DeleteTopic
      - SNS:GetTopicAttributes
      - SNS:ListTopics
      - SNS:ListSubscriptionsByTopic
      - states:DescribeExecution
      - states:DescribeStateMachine
      - states:DeleteStateMachine
      - states:ListExecutions
      - states:ListStateMachines
      - states:ListTagsForResource
      - states:TagResource
      - states:UntagResource
      - logs:DescribeLogGroups
      - elasticfilesystem:DescribeFileSystems
      - elasticfilesystem:DescribeMountTargets
      - elasticfilesystem:DescribeMountTargetSecurityGroups
      - elasticfilesystem:DescribeTags
      - elasticfilesystem:CreateFileSystem
      - elasticfilesystem:CreateMountTarget
      - elasticfilesystem:CreateTags
      - elasticfilesystem:DeleteFileSystem
      - elasticfilesystem:DeleteMountTarget
      - kinesis:CreateStream
      - kinesis:DeleteStream
      - kinesis:AddTagsToStream
      - kinesis:ListTagsForStream
      - kinesis:RemoveTagsFromStream
      - kinesis:StartStreamEncryption
      - kinesis:StopStreamEncryption
      - glue:DeleteJob
      - glue:UpdateJob
      - glue:GetJob
    Resource:
      - 'arn:aws:ssm:{{ aws_region }}:{{ aws_account_id }}:parameter/*'
      - 'arn:aws:codebuild:{{ aws_region }}:{{ aws_account_id }}:*'
      - 'arn:aws:codecommit:{{ aws_region }}:{{ aws_account_id }}:*'
      - 'arn:aws:codepipeline:{{ aws_region }}:{{ aws_account_id }}:*'
      - 'arn:aws:sns:{{ aws_region }}:{{ aws_account_id }}:*'
      - 'arn:aws:sqs:{{ aws_region }}:{{ aws_account_id }}:*'
      - 'arn:aws:logs:{{ aws_region }}:{{ aws_account_id }}:log-group:*'
      - 'arn:aws:states:{{ aws_region }}:{{ aws_account_id }}:*'
      - 'arn:aws:kinesis:{{ aws_region }}:{{ aws_account_id }}:stream/*'
      - arn:aws:glue:us-east-1:{{ aws_account_id }}:job/*
  - Sid: AllowGlobalRestrictedResourceActionsWhichIncurFees
    Effect: Allow
    Action:
      - states:CreateStateMachine
      - states:StartExecution
      - states:StopExecution
      - states:UpdateStateMachine
      - kinesis:CreateStream
      - kinesis:DecreaseStreamRetentionPeriod
      - kinesis:DeleteStream
      - kinesis:IncreaseStreamRetentionPeriod
      - kinesis:UpdateShardCount
      - glue:CreateJob
    Resource:
      - 'arn:aws:states:{{ aws_region }}:{{ aws_account_id }}:*'
      - 'arn:aws:kinesis:{{ aws_region }}:{{ aws_account_id }}:stream/*'
      - arn:aws:glue:us-east-1:{{ aws_account_id }}:job/*
  - Sid: ModifyCloudwatchLogs
    Effect: Allow
    Action:
      - logs:CreateLogGroup
      - logs:DeleteLogGroup
      - logs:PutRetentionPolicy
      - logs:DescribeMetricFilters
      - logs:DeleteMetricFilter
      - logs:PutMetricFilter
    Resource:
      - 'arn:aws:logs:{{ aws_region }}:{{ aws_account_id }}:log-group:ansible-test*'
  - Sid: ModifyCloudwatchAlarms
    Effect: Allow
    Action:
      - cloudwatch:PutMetricAlarm
      - cloudwatch:DeleteAlarms
    Resource:
      - 'arn:aws:cloudwatch:{{ aws_region }}:{{ aws_account_id }}:alarm:ansible-test*'
  - Sid: DescribeCloudwatchAlarms
    Effect: Allow
    Action:
      - cloudwatch:DescribeAlarms
    Resource:
      - 'arn:aws:cloudwatch:{{ aws_region }}:{{ aws_account_id }}:alarm:*'
  - Sid: Cloudformation
    Effect: Allow
    Action:
      - cloudformation:CreateChangeSet
      - cloudformation:CreateStack
      - cloudformation:DeleteChangeSet
      - cloudformation:DeleteStack
      - cloudformation:DescribeChangeSet
      - cloudformation:DescribeStackEvents
      - cloudformation:DescribeStacks
      - cloudformation:GetStackPolicy
      - cloudformation:SetStackPolicy
      - cloudformation:GetTemplate
      - cloudformation:ListChangeSets
      - cloudformation:ListStackResources
      - cloudformation:UpdateStack
      - cloudformation:UpdateTerminationProtection
    Resource:
      - 'arn:aws:cloudformation:{{ aws_region }}:{{ aws_account_id }}:stack/*'
